import uuid
from datetime import datetime
from typing import Optional, TYPE_CHECKING
from sqlalchemy import String, DateTime, JSON, Text, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base

if TYPE_CHECKING:
    from app.models.strategy import Strategy

class OptimizationRun(Base):
    __tablename__ = "optimization_runs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    strategy_id: Mapped[str] = mapped_column(String(36), ForeignKey("strategies.id", ondelete="CASCADE"), nullable=False)
    param_search_space: Mapped[dict] = mapped_column(JSON, nullable=False) # e.g. {"rsi_period": [10, 30], "ema_fast": [5, 20]}
    method: Mapped[str] = mapped_column(String(50), default="OPTUNA") # OPTUNA, GRID, RANDOM
    n_trials: Mapped[int] = mapped_column(Integer, default=30)
    target_metric: Mapped[str] = mapped_column(String(50), default="sharpe_ratio") # sharpe_ratio, cagr, win_rate
    
    status: Mapped[str] = mapped_column(String(50), default="PENDING") # PENDING, RUNNING, COMPLETED, FAILED
    
    top_n_results: Mapped[list] = mapped_column(JSON, default=list) # [{rank: 1, params: {}, train_metrics: {}, test_metrics: {}}]
    ai_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True) # Plain English summary generated by Claude API
    ai_recommended_config_idx: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    strategy: Mapped["Strategy"] = relationship("Strategy", back_populates="optimization_runs")
